// Single source of truth for the badge/achievement catalog. Badges are
// code-defined, not Firestore-backed, so award semantics changes go through
// code review (same reasoning as lib/networks.js for the fixed networks).
// See resources/badging.md for the full design and award-model rationale.
//
// awardMode:
//   "event"  — awarded inline by a server route at the moment the action happens
//   "lazy"   — evaluated on dashboard load against ride/booking/user history
//   "manual" — awarded by an admin action, not auto-evaluated (see resources/badging.md)

export const BADGES = [
  // --- Onboarding ---
  {
    id: "registered",
    name: "Registered",
    description: "Complete your MHSP Ride registration.",
    earnedDescription: "Welcome aboard — your account is set up.",
    image: "registered-badge.png",
    category: "onboarding",
    awardMode: "event",
    hidden: false,
    version: 1,
  },
  {
    id: "photogenic",
    name: "Photogenic",
    description: "Add a profile photo.",
    earnedDescription: "Looking good — your profile photo is live.",
    image: "photogenic-badge.png",
    category: "onboarding",
    awardMode: "event",
    hidden: false,
    version: 1,
  },
  {
    id: "lost-it",
    name: "Lost It",
    description: "Go through the forgot-password workflow.",
    earnedDescription: "You lost it, but you found your way back in.",
    image: "lost-it-badge.png",
    category: "onboarding",
    awardMode: "event",
    hidden: false,
    version: 1,
  },

  // --- Network favorites ---
  {
    id: "nordic-patrol-networker",
    name: "Nordic Patrol Networker",
    description: "Add the Nordic Patrol network to your dashboard favorites.",
    earnedDescription: "Nordic Patrol is on your dashboard for good.",
    image: "nordic-patrol-networker-badge.png",
    category: "network",
    awardMode: "event",
    hidden: false,
    version: 1,
  },
  {
    id: "hill-patrol-networker",
    name: "Hill Patrol Networker",
    description: "Add the Hill Patrol network to your dashboard favorites.",
    earnedDescription: "Hill Patrol is on your dashboard for good.",
    image: "hill-patrol-networker-badge.png",
    category: "network",
    awardMode: "event",
    hidden: false,
    version: 1,
  },
  {
    id: "mountain-host-networker",
    name: "Mountain Host Networker",
    description: "Add the Mountain Host network to your dashboard favorites.",
    earnedDescription: "Mountain Host is on your dashboard for good.",
    image: "mountain-host-networker-badge.png",
    category: "network",
    awardMode: "event",
    hidden: false,
    version: 1,
  },
  {
    id: "mountain-biking-networker",
    name: "Mountain Biking Networker",
    description: "Add the Mountain Biking network to your dashboard favorites.",
    earnedDescription: "Mountain Biking is on your dashboard for good.",
    image: "mountain-biking-networker-badge.png",
    category: "network",
    awardMode: "event",
    hidden: false,
    version: 1,
  },

  // --- Ride/drive milestones ---
  {
    id: "first-ride-offered",
    name: "First Ride Offered",
    description: "Offer your first ride.",
    earnedDescription: "First ride offered — thanks for driving.",
    image: "first-ride-offered-badge.png",
    category: "milestone",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "first-ride-booked",
    name: "First Ride Booked",
    description: "Book your first ride.",
    earnedDescription: "First ride booked — enjoy the trip.",
    image: "first-ride-booked-badge.png",
    category: "milestone",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "first-drive-completed",
    name: "First Drive Completed",
    description: "Complete your first ride as a driver.",
    earnedDescription: "First drive completed — one down.",
    image: "first-drive-completed-badge.png",
    category: "milestone",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "first-ride-completed",
    name: "First Ride Completed",
    description: "Complete your first ride as a rider.",
    earnedDescription: "First ride completed — hope it was smooth.",
    image: "first-ride-completed-badge.png",
    category: "milestone",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "fifth-drive-completed",
    name: "Fifth Drive Completed",
    description: "Complete five rides as a driver.",
    earnedDescription: "Five drives completed — you're a regular.",
    image: "fifth-drive-completed-badge.png",
    category: "milestone",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "fifth-ride-completed",
    name: "Fifth Ride Completed",
    description: "Complete five rides as a rider.",
    earnedDescription: "Five rides completed — you're a regular.",
    image: "fifth-ride-completed-badge.png",
    category: "milestone",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "ten-drives-or-rides",
    name: "10 Drives or Rides Completed",
    description: "Complete ten rides, driving or riding, combined.",
    earnedDescription: "Ten rides completed. Keep it up.",
    image: "ten-drives-or-rides-badge.png",
    category: "milestone",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "twenty-five-drives-or-rides",
    name: "25 Drives or Rides Completed",
    description: "Complete twenty-five rides, driving or riding, combined.",
    earnedDescription: "Twenty-five rides completed. Impressive.",
    image: "25-drives-or-rides-badge.png",
    category: "milestone",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "fifty-drives-or-rides",
    name: "50 Drives or Rides Completed",
    description: "Complete fifty rides, driving or riding, combined.",
    earnedDescription: "Fifty rides completed. That's a lot of mountain miles.",
    image: "50-drives-or-rides-badge.png",
    category: "milestone",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },

  // --- Favorites & social ---
  {
    id: "picking-favorites",
    name: "Picking Favorites",
    description: "Add a favorite driver.",
    earnedDescription: "You've picked a favorite driver.",
    image: "picking-favorites-badge.png",
    category: "social",
    awardMode: "event",
    hidden: false,
    version: 1,
  },
  {
    id: "favorited",
    name: "Favorited",
    description: "Get added as someone's favorite driver.",
    earnedDescription: "Someone added you as a favorite driver.",
    image: "favorited-badge.png",
    category: "social",
    awardMode: "event",
    hidden: false,
    version: 1,
  },
  {
    id: "high-five-driver",
    name: "High-5 Driver",
    description: "Get favorited by five different riders.",
    earnedDescription: "Five riders call you a favorite.",
    image: "high-five-driver-badge.png",
    category: "social",
    awardMode: "event",
    hidden: false,
    version: 1,
  },
  {
    id: "everybodys-favorite",
    name: "Everybody's Favorite",
    description: "Get favorited by ten different riders.",
    earnedDescription: "Ten riders call you a favorite. Everybody's favorite, indeed.",
    image: "everybodys-favorite-badge.png",
    category: "social",
    awardMode: "event",
    hidden: false,
    version: 1,
  },
  {
    id: "creature-of-habit",
    name: "Creature of Habit",
    description: "Book with the same driver five times.",
    earnedDescription: "Same driver, five times. You know what you like.",
    image: "creature-of-habit-badge.png",
    category: "social",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },

  // --- Communication ---
  {
    id: "communicator",
    name: "Communicator",
    description: "Submit feedback via the Contact Us form or feedback widget.",
    earnedDescription: "Thanks for speaking up.",
    image: "communicator-badge.png",
    category: "communication",
    awardMode: "event",
    hidden: false,
    version: 1,
  },
  {
    id: "the-diplomat",
    name: "The Diplomat",
    description: "Acknowledge three ride-update notices without canceling.",
    earnedDescription: "Plans changed. You rolled with it, three times over.",
    image: "the-diplomat-badge.png",
    category: "communication",
    awardMode: "lazy",
    hidden: true,
    version: 1,
  },

  // --- Exploration & vehicles ---
  {
    id: "off-the-beaten-path",
    name: "Off the Beaten Path",
    description: "Complete a ride with a custom origin or destination.",
    earnedDescription: "You went somewhere the map didn't already know about.",
    image: "off-the-beaten-path-badge.png",
    category: "exploration",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "cartographer",
    name: "The Cartographer",
    description: "Suggest a location that gets added to the map.",
    earnedDescription: "Your suggested location made it onto the map for everyone.",
    image: "cartographer-badge.png",
    category: "exploration",
    awardMode: "manual",
    hidden: true,
    version: 1,
  },
  {
    id: "frequent-flyer",
    name: "Frequent Flyer",
    description: "Book rides across all four networks.",
    earnedDescription: "Nordic, Hill, Mountain Host, Mountain Biking — you've ridden them all.",
    image: "frequent-flyer-badge.png",
    category: "exploration",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "auto-dexterous",
    name: "Auto-dexterous",
    description: "Offer rides using two different vehicles.",
    earnedDescription: "Two vehicles, one driver.",
    image: "auto-dexterous-badge.png",
    category: "exploration",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "garage-full",
    name: "Garage Full",
    description: "Register three or more vehicles on your profile.",
    earnedDescription: "Your garage is looking full.",
    image: "garage-full-badge.png",
    category: "exploration",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "round-tripper",
    name: "Round Tripper",
    description: "Complete a round-trip ride.",
    earnedDescription: "There and back again.",
    image: "round-tripper-badge.png",
    category: "exploration",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },

  // --- Timing & schedule quirks ---
  {
    id: "sunrise-patrol",
    name: "Sunrise Patrol",
    description: "Complete a ride with a departure before 6am.",
    earnedDescription: "Up before the sun.",
    image: "sunrise-patrol-badge.png",
    category: "timing",
    awardMode: "lazy",
    hidden: true,
    version: 1,
  },
  {
    id: "night-owl",
    name: "Night Owl",
    description: "Complete a ride with a departure after 8pm.",
    earnedDescription: "Still on the road after dark.",
    image: "night-owl-badge.png",
    category: "timing",
    awardMode: "lazy",
    hidden: true,
    version: 1,
  },
  {
    id: "cutting-it-close",
    name: "Cutting It Close",
    description: "Book or offer a ride right at the cancellation cutoff window.",
    earnedDescription: "Right down to the wire.",
    image: "cutting-it-close-badge.png",
    category: "timing",
    awardMode: "lazy",
    hidden: true,
    version: 1,
  },
  {
    id: "on-a-roll",
    name: "On a Roll",
    description: "Offer a ride four consecutive weeks in a row.",
    earnedDescription: "Four weeks running. You're on a roll.",
    image: "on-a-roll-badge.png",
    category: "timing",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },

  // --- Vehicle & cargo ---
  {
    id: "fully-loaded",
    name: "Fully Loaded",
    description: "Fill every seat on an offered ride.",
    earnedDescription: "Not an empty seat in the car.",
    image: "fully-loaded-badge.png",
    category: "vehicle",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "pack-mule",
    name: "Pack Mule",
    description: "Offer a ride in a vehicle with generous cargo storage.",
    earnedDescription: "Room for all the gear.",
    image: "pack-mule-badge.png",
    category: "vehicle",
    awardMode: "lazy",
    hidden: true,
    version: 1,
  },

  // --- Resilience / comedy of errors ---
  {
    id: "bounced-back",
    name: "Bounced Back",
    description: "Book or offer a ride again within a week of a cancellation.",
    earnedDescription: "Plans fell through. You didn't.",
    image: "bounced-back-badge.png",
    category: "whimsical",
    awardMode: "lazy",
    hidden: true,
    version: 1,
  },
  {
    id: "persistent",
    name: "Persistent",
    description: "Cancel and re-offer a ride on the same day.",
    earnedDescription: "Change of plans, same day, back at it.",
    image: "persistent-badge.png",
    category: "whimsical",
    awardMode: "lazy",
    hidden: true,
    version: 1,
  },

  // --- Small, dumb, delightful ---
  {
    id: "dark-side",
    name: "Gone to the Dark Side",
    description: "Switch the app theme to dark mode.",
    earnedDescription: "Welcome to the dark side.",
    image: "dark-side-badge.png",
    category: "whimsical",
    awardMode: "lazy",
    hidden: true,
    version: 1,
  },

  // --- Ride requests (issue #160) ---
  {
    id: "first-ride-requested",
    name: "First Ride Requested",
    description: "Post your first ride request.",
    earnedDescription: "First ride requested — hope someone picks it up.",
    image: "first-ride-requested-badge.png",
    category: "milestone",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "five-rides-requested",
    name: "Five Rides Requested",
    description: "Post five ride requests.",
    earnedDescription: "Five ride requests posted. You know the drill.",
    image: "five-rides-requested-badge.png",
    category: "milestone",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "ten-rides-requested",
    name: "Ten Rides Requested",
    description: "Post ten ride requests.",
    earnedDescription: "Ten ride requests posted. A regular requester.",
    image: "ten-rides-requested-badge.png",
    category: "milestone",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "needy-rider",
    name: "Needy Rider!",
    description: "Post twenty-five ride requests.",
    earnedDescription: "Twenty-five ride requests posted. Needy rider, indeed.",
    image: "needy-rider-badge.png",
    category: "milestone",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "mountain-mover",
    name: "Mountain Mover",
    description: "Fulfill a ride request for the first time.",
    earnedDescription: "First request fulfilled — you moved a mountain.",
    image: "mountain-mover-badge.png",
    category: "milestone",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "carpool-hero",
    name: "Carpool Hero",
    description: "Fulfill a ride request for the fifth time.",
    earnedDescription: "Five requests fulfilled. A carpool hero.",
    image: "carpool-hero-badge.png",
    category: "milestone",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "carpool-captain",
    name: "Carpool Captain",
    description: "Fulfill a ride request for the tenth time.",
    earnedDescription: "Ten requests fulfilled. Carpool captain material.",
    image: "carpool-captain-badge.png",
    category: "milestone",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "switching-it-up",
    name: "Switching It Up",
    description: "Fulfill a ride request but change one of the requested details.",
    earnedDescription: "You fulfilled the request — your way.",
    image: "switching-it-up-badge.png",
    category: "communication",
    awardMode: "event",
    hidden: false,
    version: 1,
  },
  {
    id: "rolling-with-it",
    name: "Rolling With It",
    description: "Your fulfilled ride request came back with changed details, and you didn't cancel.",
    earnedDescription: "Plans changed. You rolled with it.",
    image: "rolling-with-it-badge.png",
    category: "communication",
    awardMode: "lazy",
    hidden: true,
    version: 1,
  },
  {
    id: "room-to-spare",
    name: "Room to Spare",
    description: "Offer more seats than a ride request asked for.",
    earnedDescription: "Extra room, just in case.",
    image: "room-to-spare-badge.png",
    category: "vehicle",
    awardMode: "event",
    hidden: true,
    version: 1,
  },
  {
    id: "rescue-squad",
    name: "Rescue Squad",
    description: "Fulfill ride requests from three different riders.",
    earnedDescription: "Three different riders, all rescued.",
    image: "rescue-squad-badge.png",
    category: "social",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "repeat-fulfiller",
    name: "Repeat Fulfiller",
    description: "Fulfill the same rider's request three times.",
    earnedDescription: "Same rider, three times. They know who to count on.",
    image: "repeat-fulfiller-badge.png",
    category: "social",
    awardMode: "lazy",
    hidden: false,
    version: 1,
  },
  {
    id: "quick-draw",
    name: "Quick Draw",
    description: "Fulfill a ride request within 15 minutes of it being posted.",
    earnedDescription: "You didn't even let it cool down.",
    image: "quick-draw-badge.png",
    category: "timing",
    awardMode: "lazy",
    hidden: true,
    version: 1,
  },
  {
    id: "down-to-the-wire",
    name: "Down to the Wire",
    description: "Fulfill a ride request within the last hour before its 6-hour expiry cutoff.",
    earnedDescription: "Rescued with time to spare. Barely.",
    image: "down-to-the-wire-badge.png",
    category: "timing",
    awardMode: "lazy",
    hidden: true,
    version: 1,
  },
]

export const BADGE_IDS = BADGES.map((b) => b.id)

export function badgeById(id) {
  return BADGES.find((b) => b.id === id)
}

export function badgeImagePath(badge) {
  return `/assets/badges/${badge.image}`
}
