/**
 * Drive time lookup table (minutes, no traffic, driving mode).
 * Generated by scripts/buildDriveTimes.mjs — do not edit manually.
 */
export const DRIVE_TIMES = {
  "powell-butte": {
    "buzz-bowman": 58,
    "summit-pass": 59,
    "timberline": 69,
    "ski-bowl": 58,
    "meadows": 74,
    "tea-cup": 71
  },
  "clackamas-tc": {
    "buzz-bowman": 61,
    "summit-pass": 63,
    "timberline": 73,
    "ski-bowl": 61,
    "meadows": 77,
    "tea-cup": 74
  },
  "troutdale-fred-meyer": {
    "buzz-bowman": 58,
    "summit-pass": 60,
    "timberline": 70,
    "ski-bowl": 58,
    "meadows": 74,
    "tea-cup": 71
  },
  "sandy-fred-meyer": {
    "buzz-bowman": 33,
    "summit-pass": 35,
    "timberline": 44,
    "ski-bowl": 33,
    "meadows": 49,
    "tea-cup": 46
  },
  "sandy-safeway": {
    "buzz-bowman": 35,
    "summit-pass": 37,
    "timberline": 47,
    "ski-bowl": 35,
    "meadows": 51,
    "tea-cup": 48
  },
  "zigzag-ranger-station": {
    "buzz-bowman": 14,
    "summit-pass": 16,
    "timberline": 26,
    "ski-bowl": 14,
    "meadows": 30,
    "tea-cup": 27
  },
  "hoodland-thriftway": {
    "buzz-bowman": 15,
    "summit-pass": 17,
    "timberline": 27,
    "ski-bowl": 15,
    "meadows": 31,
    "tea-cup": 28
  },
  "chevron-govt-camp": {
    "buzz-bowman": 3,
    "summit-pass": 5,
    "timberline": 12,
    "ski-bowl": 4,
    "meadows": 16,
    "tea-cup": 13
  },
  "buzz-bowman-center": {
    "buzz-bowman": 0,
    "summit-pass": 5,
    "timberline": 14,
    "ski-bowl": 4,
    "meadows": 18,
    "tea-cup": 15
  },
  "hood-river-safeway": {
    "buzz-bowman": 54,
    "summit-pass": 54,
    "timberline": 63,
    "ski-bowl": 55,
    "meadows": 47,
    "tea-cup": 40
  },
  "buzz-bowman": {
    "powell-butte": 58,
    "clackamas-tc": 61,
    "troutdale-fred-meyer": 55,
    "sandy-fred-meyer": 33,
    "sandy-safeway": 33,
    "zigzag-ranger-station": 14,
    "hoodland-thriftway": 16,
    "chevron-govt-camp": 2,
    "buzz-bowman-center": 0,
    "hood-river-safeway": 55
  },
  "summit-pass": {
    "powell-butte": 59,
    "clackamas-tc": 63,
    "troutdale-fred-meyer": 57,
    "sandy-fred-meyer": 34,
    "sandy-safeway": 34,
    "zigzag-ranger-station": 15,
    "hoodland-thriftway": 17,
    "chevron-govt-camp": 1,
    "buzz-bowman-center": 3,
    "hood-river-safeway": 54
  },
  "timberline": {
    "powell-butte": 70,
    "clackamas-tc": 73,
    "troutdale-fred-meyer": 67,
    "sandy-fred-meyer": 45,
    "sandy-safeway": 44,
    "zigzag-ranger-station": 26,
    "hoodland-thriftway": 27,
    "chevron-govt-camp": 12,
    "buzz-bowman-center": 14,
    "hood-river-safeway": 64
  },
  "ski-bowl": {
    "powell-butte": 58,
    "clackamas-tc": 62,
    "troutdale-fred-meyer": 56,
    "sandy-fred-meyer": 33,
    "sandy-safeway": 33,
    "zigzag-ranger-station": 14,
    "hoodland-thriftway": 16,
    "chevron-govt-camp": 4,
    "buzz-bowman-center": 3,
    "hood-river-safeway": 56
  },
  "meadows": {
    "powell-butte": 73,
    "clackamas-tc": 76,
    "troutdale-fred-meyer": 70,
    "sandy-fred-meyer": 48,
    "sandy-safeway": 48,
    "zigzag-ranger-station": 29,
    "hoodland-thriftway": 31,
    "chevron-govt-camp": 15,
    "buzz-bowman-center": 17,
    "hood-river-safeway": 47
  },
  "tea-cup": {
    "powell-butte": 71,
    "clackamas-tc": 74,
    "troutdale-fred-meyer": 68,
    "sandy-fred-meyer": 46,
    "sandy-safeway": 46,
    "zigzag-ranger-station": 27,
    "hoodland-thriftway": 29,
    "chevron-govt-camp": 13,
    "buzz-bowman-center": 15,
    "hood-river-safeway": 40
  }
};

export function getDriveMinutes(fromId, toId) {
  return DRIVE_TIMES[fromId]?.[toId] ?? null;
}

export function estimateArrival(departureTime, fromId, toId) {
  const minutes = getDriveMinutes(fromId, toId);
  if (!minutes || !departureTime) return null;
  const [h, m] = departureTime.split(":").map(Number);
  const total = h * 60 + m + minutes;
  const ah = String(Math.floor(total / 60) % 24).padStart(2, "0");
  const am = String(total % 60).padStart(2, "0");
  return `${ah}:${am}`;
}
