/**
 * Drive time lookup table (minutes, no traffic, driving mode).
 * Generated by scripts/buildDriveTimes.mjs on 2026-07-26.
 * Do not edit manually — re-run the script to refresh.
 */
export const DRIVE_TIMES = {
  "powell-butte": {
    "buzz-bowman": 57,
    "summit-pass": 59,
    "timberline": 68,
    "ski-bowl": 57,
    "meadows": 72,
    "tea-cup": 69
  },
  "clackamas-tc": {
    "buzz-bowman": 61,
    "summit-pass": 63,
    "timberline": 72,
    "ski-bowl": 61,
    "meadows": 76,
    "tea-cup": 73
  },
  "troutdale-fred-meyer": {
    "buzz-bowman": 58,
    "summit-pass": 60,
    "timberline": 70,
    "ski-bowl": 58,
    "meadows": 73,
    "tea-cup": 70
  },
  "sandy-fred-meyer": {
    "buzz-bowman": 32,
    "summit-pass": 34,
    "timberline": 44,
    "ski-bowl": 32,
    "meadows": 47,
    "tea-cup": 44
  },
  "sandy-safeway": {
    "buzz-bowman": 35,
    "summit-pass": 36,
    "timberline": 46,
    "ski-bowl": 34,
    "meadows": 49,
    "tea-cup": 47
  },
  "zigzag-ranger-station": {
    "buzz-bowman": 13,
    "summit-pass": 15,
    "timberline": 25,
    "ski-bowl": 13,
    "meadows": 28,
    "tea-cup": 26
  },
  "hoodland-thriftway": {
    "buzz-bowman": 15,
    "summit-pass": 17,
    "timberline": 26,
    "ski-bowl": 15,
    "meadows": 30,
    "tea-cup": 27
  },
  "chevron-govt-camp": {
    "buzz-bowman": 2,
    "summit-pass": 4,
    "timberline": 12,
    "ski-bowl": 4,
    "meadows": 15,
    "tea-cup": 13
  },
  "buzz-bowman-center": {
    "buzz-bowman": 0,
    "summit-pass": 5,
    "timberline": 13,
    "ski-bowl": 3,
    "meadows": 17,
    "tea-cup": 14
  },
  "sandy-bi-mart": {
    "buzz-bowman": 34,
    "summit-pass": 35,
    "timberline": 45,
    "ski-bowl": 33,
    "meadows": 48,
    "tea-cup": 46
  },
  "gresham-transit": {
    "buzz-bowman": 51,
    "summit-pass": 53,
    "timberline": 62,
    "ski-bowl": 51,
    "meadows": 66,
    "tea-cup": 63
  },
  "welches-rd": {
    "buzz-bowman": 15,
    "summit-pass": 17,
    "timberline": 26,
    "ski-bowl": 15,
    "meadows": 30,
    "tea-cup": 27
  },
  "hood-river-safeway": {
    "buzz-bowman": 53,
    "summit-pass": 52,
    "timberline": 61,
    "ski-bowl": 54,
    "meadows": 45,
    "tea-cup": 40
  },
  "buzz-bowman": {
    "powell-butte": 57,
    "clackamas-tc": 61,
    "troutdale-fred-meyer": 55,
    "sandy-fred-meyer": 32,
    "sandy-safeway": 32,
    "zigzag-ranger-station": 13,
    "hoodland-thriftway": 15,
    "chevron-govt-camp": 2,
    "buzz-bowman-center": 0,
    "sandy-bi-mart": 32,
    "gresham-transit": 51,
    "welches-rd": 15,
    "hood-river-safeway": 53
  },
  "summit-pass": {
    "powell-butte": 59,
    "clackamas-tc": 62,
    "troutdale-fred-meyer": 56,
    "sandy-fred-meyer": 34,
    "sandy-safeway": 34,
    "zigzag-ranger-station": 15,
    "hoodland-thriftway": 16,
    "chevron-govt-camp": 1,
    "buzz-bowman-center": 3,
    "sandy-bi-mart": 33,
    "gresham-transit": 52,
    "welches-rd": 16,
    "hood-river-safeway": 51
  },
  "timberline": {
    "powell-butte": 68,
    "clackamas-tc": 72,
    "troutdale-fred-meyer": 66,
    "sandy-fred-meyer": 43,
    "sandy-safeway": 43,
    "zigzag-ranger-station": 24,
    "hoodland-thriftway": 26,
    "chevron-govt-camp": 11,
    "buzz-bowman-center": 13,
    "sandy-bi-mart": 43,
    "gresham-transit": 62,
    "welches-rd": 26,
    "hood-river-safeway": 61
  },
  "ski-bowl": {
    "powell-butte": 57,
    "clackamas-tc": 61,
    "troutdale-fred-meyer": 55,
    "sandy-fred-meyer": 32,
    "sandy-safeway": 32,
    "zigzag-ranger-station": 13,
    "hoodland-thriftway": 15,
    "chevron-govt-camp": 3,
    "buzz-bowman-center": 2,
    "sandy-bi-mart": 32,
    "gresham-transit": 51,
    "welches-rd": 15,
    "hood-river-safeway": 53
  },
  "meadows": {
    "powell-butte": 71,
    "clackamas-tc": 75,
    "troutdale-fred-meyer": 69,
    "sandy-fred-meyer": 46,
    "sandy-safeway": 46,
    "zigzag-ranger-station": 27,
    "hoodland-thriftway": 29,
    "chevron-govt-camp": 14,
    "buzz-bowman-center": 16,
    "sandy-bi-mart": 46,
    "gresham-transit": 65,
    "welches-rd": 29,
    "hood-river-safeway": 45
  },
  "tea-cup": {
    "powell-butte": 70,
    "clackamas-tc": 73,
    "troutdale-fred-meyer": 67,
    "sandy-fred-meyer": 45,
    "sandy-safeway": 45,
    "zigzag-ranger-station": 26,
    "hoodland-thriftway": 27,
    "chevron-govt-camp": 13,
    "buzz-bowman-center": 14,
    "sandy-bi-mart": 44,
    "gresham-transit": 63,
    "welches-rd": 27,
    "hood-river-safeway": 39
  }
};

/**
 * Returns estimated drive time in minutes between two location IDs.
 * Returns null if the pair is not in the table.
 * @param {string} fromId
 * @param {string} toId
 * @returns {number|null}
 */
export function getDriveMinutes(fromId, toId) {
  return DRIVE_TIMES[fromId]?.[toId] ?? null;
}

/**
 * Given a departure time string ("HH:MM") and a from/to pair,
 * returns the estimated arrival time string ("HH:MM"), or null.
 * @param {string} departureTime  e.g. "06:30"
 * @param {string} fromId
 * @param {string} toId
 * @returns {string|null}
 */
export function estimateArrival(departureTime, fromId, toId) {
  const minutes = getDriveMinutes(fromId, toId);
  if (!minutes || !departureTime) return null;
  const [h, m] = departureTime.split(":").map(Number);
  const total = h * 60 + m + minutes;
  const ah = String(Math.floor(total / 60) % 24).padStart(2, "0");
  const am = String(total % 60).padStart(2, "0");
  return `${ah}:${am}`;
}
