/**
 * buildDriveTimes.mjs
 *
 * Hits the Google Directions API for every departure→arrival pair and writes
 * the results to lib/drive-times.js as a static lookup table.
 *
 * Usage:
 *   node scripts/buildDriveTimes.mjs
 *
 * Requires GOOGLE_MAPS_API_KEY in environment or reads from
 * resources/google-maps-api-key.txt
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

// ── Load API key ────────────────────────────────────────────────────────────
const API_KEY =
  process.env.GOOGLE_MAPS_API_KEY ||
  fs.readFileSync(path.join(ROOT, "resources/google-maps-api-key.txt"), "utf8").trim();

// ── Location definitions ─────────────────────────────────────────────────────
const DEPARTURE_LOCATIONS = [
  { id: "powell-butte",            lat: 45.4947932,  lon: -122.4966988 },
  { id: "clackamas-tc",            lat: 45.4331658,  lon: -122.579242  },
  { id: "troutdale-fred-meyer",    lat: 45.5515379,  lon: -122.3880687 },
  { id: "sandy-fred-meyer",        lat: 45.3895446,  lon: -122.2634993 },
  { id: "sandy-safeway",           lat: 45.3973402,  lon: -122.2683607 },
  { id: "zigzag-ranger-station",   lat: 45.3428437,  lon: -121.9415786 },
  { id: "hoodland-thriftway",      lat: 45.3476142,  lon: -121.9628787 },
  { id: "chevron-govt-camp",       lat: 45.302644,   lon: -121.7466654 },
  { id: "buzz-bowman-center",      lat: 45.3048918,  lon: -121.7590055 },
  { id: "hood-river-safeway",      lat: 45.7087368,  lon: -121.5349924 },
];

const ARRIVAL_LOCATIONS = [
  { id: "buzz-bowman",   lat: 45.3048918,  lon: -121.7590055 },
  { id: "summit-pass",   lat: 45.3029059,  lon: -121.7458283 },
  { id: "timberline",    lat: 45.3311281,  lon: -121.7110064 },
  { id: "ski-bowl",      lat: 45.3019084,  lon: -121.773296  },
  { id: "meadows",       lat: 45.3317552,  lon: -121.6651848 },
  { id: "tea-cup",       lat: 45.3203457,  lon: -121.6231353 },
];

// ── Directions API fetch ─────────────────────────────────────────────────────
async function getDriveMinutes(origin, destination) {
  const url = new URL("https://maps.googleapis.com/maps/api/directions/json");
  url.searchParams.set("origin", `${origin.lat},${origin.lon}`);
  url.searchParams.set("destination", `${destination.lat},${destination.lon}`);
  url.searchParams.set("mode", "driving");
  url.searchParams.set("key", API_KEY);

  const res = await fetch(url.toString());
  const data = await res.json();

  if (data.status !== "OK") {
    throw new Error(`Directions API error: ${data.status} — ${data.error_message || ""}`);
  }

  const seconds = data.routes[0].legs[0].duration.value;
  return Math.round(seconds / 60);
}

// ── Build the matrix ─────────────────────────────────────────────────────────
async function buildMatrix() {
  const result = {};

  // Outbound: departure → arrival
  console.log("── Outbound (departure → arrival) ──────────────────────");
  for (const from of DEPARTURE_LOCATIONS) {
    result[from.id] = result[from.id] || {};
    for (const to of ARRIVAL_LOCATIONS) {
      try {
        const minutes = await getDriveMinutes(from, to);
        result[from.id][to.id] = minutes;
        console.log(`  ${from.id} → ${to.id}: ${minutes} min`);
      } catch (err) {
        console.error(`  ERROR ${from.id} → ${to.id}: ${err.message}`);
        result[from.id][to.id] = null;
      }
      // Stay well under the 10 QPS limit
      await new Promise(r => setTimeout(r, 120));
    }
  }

  // Return: arrival → departure
  console.log("\n── Return (arrival → departure) ────────────────────────");
  for (const from of ARRIVAL_LOCATIONS) {
    result[from.id] = result[from.id] || {};
    for (const to of DEPARTURE_LOCATIONS) {
      try {
        const minutes = await getDriveMinutes(from, to);
        result[from.id][to.id] = minutes;
        console.log(`  ${from.id} → ${to.id}: ${minutes} min`);
      } catch (err) {
        console.error(`  ERROR ${from.id} → ${to.id}: ${err.message}`);
        result[from.id][to.id] = null;
      }
      await new Promise(r => setTimeout(r, 120));
    }
  }

  return result;
}

// ── Write output ─────────────────────────────────────────────────────────────
const matrix = await buildMatrix();

const output = `/**
 * Drive time lookup table (minutes, no traffic, driving mode).
 * Generated by scripts/buildDriveTimes.mjs on ${new Date().toISOString().split("T")[0]}.
 * Do not edit manually — re-run the script to refresh.
 */
export const DRIVE_TIMES = ${JSON.stringify(matrix, null, 2)};

/**
 * Returns estimated drive time in minutes between two location IDs.
 * Returns null if the pair is not in the table.
 * @param {string} fromId
 * @param {string} toId
 * @returns {number|null}
 */
export function getDriveMinutes(fromId, toId) {
  return DRIVE_TIMES[fromId]?.[toId] ?? null;
}

/**
 * Given a departure time string ("HH:MM") and a from/to pair,
 * returns the estimated arrival time string ("HH:MM"), or null.
 * @param {string} departureTime  e.g. "06:30"
 * @param {string} fromId
 * @param {string} toId
 * @returns {string|null}
 */
export function estimateArrival(departureTime, fromId, toId) {
  const minutes = getDriveMinutes(fromId, toId);
  if (!minutes || !departureTime) return null;
  const [h, m] = departureTime.split(":").map(Number);
  const total = h * 60 + m + minutes;
  const ah = String(Math.floor(total / 60) % 24).padStart(2, "0");
  const am = String(total % 60).padStart(2, "0");
  return \`\${ah}:\${am}\`;
}
`;

const outPath = path.join(ROOT, "lib/drive-times.js");
fs.writeFileSync(outPath, output);
console.log(`\n✓ Written to ${outPath}`);
console.log(`  ${Object.keys(matrix).length} origin nodes, ${Object.values(matrix).reduce((n, v) => n + Object.keys(v).length, 0)} total pairs`);
