/**
 * fillDriveTimes.mjs
 * Retries only the null entries in lib/drive-times.js
 */
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { DRIVE_TIMES } from "../lib/drive-times.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const API_KEY = fs.readFileSync(path.join(ROOT, "resources/google-maps-api-key.txt"), "utf8").trim();

const COORDS = {
  "powell-butte":          { lat: 45.4947932,  lon: -122.4966988 },
  "clackamas-tc":          { lat: 45.4331658,  lon: -122.579242  },
  "troutdale-fred-meyer":  { lat: 45.5515379,  lon: -122.3880687 },
  "sandy-fred-meyer":      { lat: 45.3895446,  lon: -122.2634993 },
  "sandy-safeway":         { lat: 45.3973402,  lon: -122.2683607 },
  "zigzag-ranger-station": { lat: 45.3428437,  lon: -121.9415786 },
  "hoodland-thriftway":    { lat: 45.3476142,  lon: -121.9628787 },
  "chevron-govt-camp":     { lat: 45.302644,   lon: -121.7466654 },
  "buzz-bowman-center":    { lat: 45.3048918,  lon: -121.7590055 },
  "hood-river-safeway":    { lat: 45.7087368,  lon: -121.5349924 },
  "buzz-bowman":           { lat: 45.3048918,  lon: -121.7590055 },
  "summit-pass":           { lat: 45.3029059,  lon: -121.7458283 },
  "timberline":            { lat: 45.3311281,  lon: -121.7110064 },
  "ski-bowl":              { lat: 45.3019084,  lon: -121.773296  },
  "meadows":               { lat: 45.3317552,  lon: -121.6651848 },
  "tea-cup":               { lat: 45.3203457,  lon: -121.6231353 },
};

async function getDriveMinutes(from, to) {
  const url = new URL("https://maps.googleapis.com/maps/api/directions/json");
  url.searchParams.set("origin", `${COORDS[from].lat},${COORDS[from].lon}`);
  url.searchParams.set("destination", `${COORDS[to].lat},${COORDS[to].lon}`);
  url.searchParams.set("mode", "driving");
  url.searchParams.set("key", API_KEY);
  const res = await fetch(url.toString());
  const data = await res.json();
  if (data.status !== "OK") throw new Error(`${data.status}: ${data.error_message || ""}`);
  return Math.round(data.routes[0].legs[0].duration.value / 60);
}

// Find nulls
const nullPairs = [];
for (const [from, tos] of Object.entries(DRIVE_TIMES)) {
  for (const [to, val] of Object.entries(tos)) {
    if (val === null) nullPairs.push([from, to]);
  }
}

console.log(`Filling ${nullPairs.length} null pairs...`);
const updated = JSON.parse(JSON.stringify(DRIVE_TIMES));

for (const [from, to] of nullPairs) {
  try {
    const minutes = await getDriveMinutes(from, to);
    updated[from][to] = minutes;
    console.log(`  ✓ ${from} → ${to}: ${minutes} min`);
  } catch (err) {
    console.error(`  ✗ ${from} → ${to}: ${err.message}`);
  }
  await new Promise(r => setTimeout(r, 150));
}

// Rewrite the file
const outPath = path.join(ROOT, "lib/drive-times.js");
const output = `/**
 * Drive time lookup table (minutes, no traffic, driving mode).
 * Generated by scripts/buildDriveTimes.mjs — do not edit manually.
 */
export const DRIVE_TIMES = ${JSON.stringify(updated, null, 2)};

export function getDriveMinutes(fromId, toId) {
  return DRIVE_TIMES[fromId]?.[toId] ?? null;
}

export function estimateArrival(departureTime, fromId, toId) {
  const minutes = getDriveMinutes(fromId, toId);
  if (!minutes || !departureTime) return null;
  const [h, m] = departureTime.split(":").map(Number);
  const total = h * 60 + m + minutes;
  const ah = String(Math.floor(total / 60) % 24).padStart(2, "0");
  const am = String(total % 60).padStart(2, "0");
  return \`\${ah}:\${am}\`;
}
`;

fs.writeFileSync(outPath, output);
const remaining = Object.values(updated).flatMap(v => Object.values(v)).filter(v => v === null).length;
console.log(`\n✓ Done. ${remaining} nulls remaining.`);
